2020-03-29 09:06:07,567 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 45, in decorator
    return f(*args, **kwargs)
  File "D:\PROGRAMMING\github\firestone_api\app\api\routes.py", line 28, in keep_alive
    _license_all_ips = [x for x in _license.all_ips]
TypeError: 'NoneType' object is not iterable
2020-03-29 09:06:07,690 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,690 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,690 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,690 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,690 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,908 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 45, in decorator
    return f(*args, **kwargs)
  File "D:\PROGRAMMING\github\firestone_api\app\api\routes.py", line 28, in keep_alive
    _license_all_ips = [x for x in _license.all_ips]
TypeError: 'NoneType' object is not iterable
2020-03-29 09:06:07,908 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 45, in decorator
    return f(*args, **kwargs)
  File "D:\PROGRAMMING\github\firestone_api\app\api\routes.py", line 28, in keep_alive
    _license_all_ips = [x for x in _license.all_ips]
TypeError: 'NoneType' object is not iterable
2020-03-29 09:06:07,908 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 45, in decorator
    return f(*args, **kwargs)
  File "D:\PROGRAMMING\github\firestone_api\app\api\routes.py", line 28, in keep_alive
    _license_all_ips = [x for x in _license.all_ips]
TypeError: 'NoneType' object is not iterable
2020-03-29 09:06:07,908 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 45, in decorator
    return f(*args, **kwargs)
  File "D:\PROGRAMMING\github\firestone_api\app\api\routes.py", line 28, in keep_alive
    _license_all_ips = [x for x in _license.all_ips]
TypeError: 'NoneType' object is not iterable
2020-03-29 09:06:07,908 ERROR: Exception on /alive [GET] [in d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programming\github\firestone_api\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PROGRAMMING\github\firestone_api\app\auth\license.py", line 45, in decorator
    return f(*args, **kwargs)
  File "D:\PROGRAMMING\github\firestone_api\app\api\routes.py", line 28, in keep_alive
    _license_all_ips = [x for x in _license.all_ips]
TypeError: 'NoneType' object is not iterable
2020-03-29 09:06:07,920 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,920 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,920 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,920 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,920 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:07,920 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:08,139 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:08,139 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:08,139 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
2020-03-29 09:06:08,139 INFO: Firestone API Started [in D:\PROGRAMMING\github\firestone_api\app\__init__.py:55]
